apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    name: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: go-app
  template:
    metadata:
      name: go-app
      labels:
        name: go-app
    spec:
      containers:
        - name: go-app
          image: {{CONTAINER_REGISTRY}}/go-app:{{VERSION}}
          ports:
            - containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  selector:
    name: go-app
  ports:
    - port: 4000
      targetPort: 4000